fix error checks

diff --git a/bin/snapshots b/bin/snapshots
--- a/bin/snapshots
+++ b/bin/snapshots
@@ -3,11 +3,13 @@
 source /etc/default/snapshots
 
 # Check for required /etc/snapshots.list
-[ -e /etc/snapshots.list ] || (echo "ERROR: /etc/snapshots.list is required" && exit 1)
+if [ ! -e /etc/snapshots.list ]; then
+    echo "ERROR: /etc/snapshots.list is required"
+    exit 1
+fi
 
 # Read btrfs volumes to snapshot from /etc/snapshots.list
-VOLUMES=$(cat /etc/snapshots.list)
-for volume in $VOLUMES; do
+for volume in $(cat /etc/snapshots.list); do
     # Check last char, must be a '/'
     if [ x"${volume: -1}" != x'/' ]; then
         echo "ERROR: check /etc/snapshots.list, ${volume} should end with a '/'"
@@ -16,7 +18,7 @@ for volume in $VOLUMES; do
 
     # Check if snapshot is already done
     btrfs subvolume show ${volume}.daily-$(date +%Y-%m-%d) > /dev/null 2>&1
-    if [ $? -ne 0 ]; then
+    if ! btrfs subvolume show ${volume}.daily-$(date +%Y-%m-%d) > /dev/null 2>&1; then
         echo -n "[$(date +'%Y-%m-%d %H:%M')] "
         btrfs subvolume snapshot -r ${volume} ${volume}.daily-$(date +%Y-%m-%d)
         sync
diff --git a/bin/snapshots-send b/bin/snapshots-send
--- a/bin/snapshots-send
+++ b/bin/snapshots-send
@@ -3,20 +3,30 @@
 source /etc/default/snapshots
 
 # Check for required /etc/snapshots.list
-[ -e /etc/snapshots.list ] || (echo "ERROR: /etc/snapshots.list is required" && exit 1)
+if [ ! -e /etc/snapshots.list ]; then
+    echo "ERROR: /etc/snapshots.list is required"
+    exit 1
+fi
 
-# Alias to run commands on SNAPSHOTS_USER@SNAPSHOTS_SERVER defined from
-# /etc/default/snapshots
+# Check for required variables that should be defined in /etc/default/snapshots
+if [ -z ${SNAPSHOTS_USER} ] || [ -z ${SNAPSHOTS_SERVER} ] || [ -z ${SNAPSHOTS_PATH} ]; then
+    echo "ERROR: SNAPSHOTS_USER, SNAPSHOTS_SERVER or SNAPSHOTS_PATH is not defined, check your /etc/default/snapshots"
+    exit 1
+fi
+
+# Alias to run commands on SNAPSHOTS_USER@SNAPSHOTS_SERVER defined from /etc/default/snapshots
 do_ssh() {
     ssh ${SNAPSHOTS_USER}@${SNAPSHOTS_SERVER} $@
 }
 
 # Check if snapshots server is up
-do_ssh true 2> /dev/null || (echo "ERROR: ${SNAPSHOTS_SERVER} unreachable" && exit 1)
+if ! do_ssh true 2> /dev/null; then
+    echo "ERROR: ${SNAPSHOTS_SERVER} unreachable"
+    exit 1
+fi
 
 # Read btrfs volumes to snapshot from /etc/snapshots.list
-VOLUMES=$(cat /etc/snapshots.list)
-for volume in ${VOLUMES}; do
+for volume in $(cat /etc/snapshots.list); do
     # Make sure remote directory exists
     do_ssh mkdir -p ${SNAPSHOTS_PATH}${volume}
 
